language: c
os:
 - linux
install: 
 - sudo apt-get update || true
 - sudo apt-get install gcc automake autoconf perl m4 autotools-dev mysql-server libmysqld-dev
script:
 - autoreconf -ivf
 - ./configure --prefix=/usr/local/zabbix --enable-server --enable-agent --with-mysql
 - make
